# Find and FindAll

In [1]:
from bs4 import BeautifulSoup

In [2]:
import requests

In [8]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [9]:
page = requests.get(url)

In [10]:
page_html = BeautifulSoup(page.text, 'html')

In [13]:
#print(page_html)

In [14]:
div = page_html.find('div')

In [23]:
#div

In [35]:
page_html.find('th').text.strip()

'Team Name'

# List of largest companies in the United States by revenue

In [ ]:
from bs4 import BeautifulSoup
import requests

In [57]:
page_url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

response = requests.get(page_url, headers=headers)

In [58]:
page_html = BeautifulSoup(response.text, 'html')

In [215]:
tb = page_html.find('table', class_ = 'wikitable sortable')

In [167]:
t_header = page_html.find('tr')

In [185]:
header_arr = [header.text.strip() for header in t_header]
header_arr = [h for h in header_arr if h.strip()]

In [187]:
import pandas as pd

In [188]:
df = pd.DataFrame(columns=header_arr)

In [190]:
table = page_html.find('table', class_='wikitable sortable')

In [191]:
t_data = table.find_all('td')

In [192]:
data_arr = [data.text for data in t_data]

In [193]:
length = len(data_arr)

In [194]:
import numpy as np

In [195]:
np_arr = np.array(data_arr).reshape(-1, 7)

In [204]:
df = pd.DataFrame(np_arr, columns=header_arr)

In [207]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [211]:
df_no_index = df.set_index('Rank')

In [212]:
df_no_index

,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Rank,,,,,,
1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...
96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [213]:
df.to_csv(r'C:\Users\Michael\Downloads\companies.csv', index=False)